DAQMS/DAQMS.Web/Controllers/MenuGroupController.cs
using Code;
using DAQMS.DomainViewModel;
using DAQMS.Service;
using DAQMS.Web.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DAQMS.Web.Controllers
{
    public class MenuGroupController : Controller
    {

        private readonly MenuGroupService _menuGroupService;

        public MenuGroupController()
        {
            this._menuGroupService = new MenuGroupService();
        }

        public ActionResult Index()
        {
            MenuGroupViewModel model = new MenuGroupViewModel();
            model.ModuleList = PopulateDropdown.PopulateDropdownListByTable("modules");
            return View(model);
        }

        public PartialViewResult List(int? page)
        {
            IList<MenuGroupViewModel> model = _menuGroupService.GetAll();
            return PartialView("_PartialList", model);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public PartialViewResult List(int? page, MenuGroupViewModel model)
        {
            IList<MenuGroupViewModel> data = _menuGroupService.GetByItem(model);
            return PartialView("_PartialList", data);
        }

        [HttpGet]
        public ActionResult Create()
        {
            MenuGroupViewModel model = new MenuGroupViewModel();
            model.ModuleList = PopulateDropdown.PopulateDropdownListByTable("modules");
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(MenuGroupViewModel model)
        {
            int returnId = -1;
            model.LoginUserID = HttpContext.User.Identity.Name;
            var strMessage = string.Empty;
            try
            {
                if (ModelState.IsValid)
                {
                    if (string.IsNullOrEmpty(strMessage))
                    {
                        returnId = _menuGroupService.InsertData(model);

                        if (returnId <= 0)
                        {
                            strMessage = "Error: There was a problem while processing your request.";
                            return Content(strMessage);
                        }
                        else
                        {
                            return Content(Boolean.TrueString);
                        }
                    }
                    else
                    {
                        return Content(strMessage);
                    }
                }
                else
                {
                    strMessage = Common.GetModelStateErrorMessage(ModelState);
                    return Content(strMessage);
                }
            }
            catch (Exception ex)
            {
                strMessage = "Error: There was a problem while processing your request: " + ex.Message;
                return Content(strMessage);
            }
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            MenuGroupViewModel model = _menuGroupService.GetIById(id);
            model.ModuleList = PopulateDropdown.PopulateDropdownListByTable("modules");
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(MenuGroupViewModel model)
        {
            int returnId = -1;
            model.LoginUserID = HttpContext.User.Identity.Name;
            var strMessage = string.Empty;
            try
            {
                if (ModelState.IsValid)
                {
                    if (string.IsNullOrEmpty(strMessage))
                    {
                        returnId = _menuGroupService.UpdateData(model);

                        if (returnId <= 0)
                        {
                            strMessage = "Error: There was a problem while processing your request.";
                            return Content(strMessage);
                        }
                        else
                        {
                            return Content(Boolean.TrueString);
                        }
                    }
                    else
                    {
                        return Content(strMessage);
                    }
                }
                else
                {
                    strMessage = Common.GetModelStateErrorMessage(ModelState);
                    return Content(strMessage);
                }
            }
            catch (Exception ex)
            {
                strMessage = "Error: There was a problem while processing your request: " + ex.Message;
                return Content(strMessage);
            }
        }

        [HttpPost, ActionName("Delete")]
        public JsonResult DeleteConfirmed(int id)
        {
            int userId = -1;
            bool result = true;
            string errMsg = string.Empty;
            try
            {

                userId = _menuGroupService.DeleteData(id);

                if (userId <= 0)
                {
                    result = false;
                    errMsg = "This information is already used in another scope.";
                }
                else
                {
                    result = true;
                    errMsg = "Information has been deleted successfully.";
                }
            }
            catch (Exception ex)
            {
                result = false;
                errMsg = ex.Message;
            }
            return Json(new
            {
                Success = result,
                Message = errMsg
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

DAQMS/DAQMS.Web/Views/MenuGroup/Create.cshtml
@model  DAQMS.DomainViewModel.MenuGroupViewModel
@{
    ViewBag.Title = "DAQ - Add Menu Group";
}
@using (Html.BeginForm("Create", "MenuGroup", FormMethod.Post, new { @id = "frmSave" }))
{
    <div class="table-header">
        Create Menu Group
    </div>
    <div class="dataTables_wrapper">
        @Html.ValidationSummary(true)
        @Html.Partial("_CreateOrEdit", Model)

        <div class="row-fluid form-horizontal">
            <div class="control-group">
                <div class="controls">
                    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-small btn-success" })
                    <button id="btnSave" name="btnSave" type="submit" class="btn btn-small btn-success" onclick="return fnValidate()">
                        Save
                    </button>
                </div>
            </div>
            <div class="control-group">
                <div class="controls">
                    <div id="ErrorMessage">
                    </div>
                    <div id="lblMsg">
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<script language="javascript" type="text/javascript">
    $(document).ready(function () {
        //required for Unit Info
        $("#frmSave").on('submit', function (e) {
            e.preventDefault();

            $("#lblMsg").html(''); $("#ErrorMessage").html('');
            var data = $(this).serialize();
            $.ajax({
                type: "POST",
                url: '@Url.Action("Create", "MenuGroup")',
                data: data,
                success: (function (result) {
                    if (result == "True") {

                        $("#lblMsg").html('Information has been saved successfully').css("color", "green");
                        $("#lblMsg").show();
                        $("#MyDialog").dialog('close');
                    }
                    else {
                        $("#ErrorMessage").html(result).css("color", "red");
                    }
                })
            })
        });
    });
</script>

DAQMS/DAQMS.Web/Views/MenuGroup/Edit.cshtml
@model DAQMS.DomainViewModel.MenuGroupViewModel
@{
    ViewBag.Title = "DAQ - Edit Menu Group";
}
@using (Html.BeginForm("Edit", "MenuGroup", FormMethod.Post, new { @id = "frmEdit" }))
{
    <div class="table-header">
        Edit Menu Group
    </div>
    <div class="dataTables_wrapper">
        @Html.ValidationSummary(true)

        @Html.HiddenFor(model => model.Id)
        @Html.Partial("_CreateOrEdit", Model)

        <div class="row-fluid form-horizontal">
            <div class="control-group">
                <div class="controls">
                    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-small btn-success" })
                    <button id="btnSave" name="btnSave" type="submit" class="btn btn-small btn-success"
                            onclick="return fnValidate()">
                        Update
                    </button>
                </div>
            </div>
            <div class="control-group">
                <div class="controls">
                    <div id="ErrorMessage">
                    </div>
                    <div id="lblMsg">
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<script language="javascript" type="text/javascript">
    $(document).ready(function () {
        //required for Unit Info
        $("#frmEdit").on('submit', function (e) {
            //Clear message
            $("#lblMsg").html(''); $("#ErrorMessage").html('');
            e.preventDefault();
            var data = $(this).serialize();
            $.ajax({
                type: "POST",
                url: '@Url.Action("Edit", "MenuGroup")',
                data: data,
                success: (function (result) {
                    if (result == "True") {
                        //show message in popup
                        $("#lblMsg").html('');
                        $("#lblMsg").html('Information has been updated successfully').css("color", "green");
                        $("#lblMsg").show();
                        $("#MyDialog").dialog('close');
                    }
                    else {
                        $("#ErrorMessage").html(result).css("color", "red");;
                    }

                    var msg = $("#lblMsg").text();
                    $("#MyDialog").dialog('close');
                })
            })
        });
    });
</script>

DAQMS/DAQMS.Web/Views/MenuGroup/Index.cshtml
@model  DAQMS.DomainViewModel.MenuGroupViewModel

@{
    ViewBag.Title = "List of Menu Group";

}

<form id="frmSearch" method="post" action="">
    <div class="table-header">
        List of Menu Group
        @Html.ActionLink("  Add New", "Create", null, new { @class = " icon-plus btn btn-small btn-success pull-right" })
    </div>

    <div class="dataTables_wrapper form-horizontal">

        <div class="row-fluid ">
            <div class="span6">
                <div class="control-group">
                    @Html.LabelFor(model => model.ModuleName, new { @class = "control-label" })
                    <div class="controls">
                        @Html.DropDownListFor(model => model.ModuleId, Model.ModuleList, new { @class = "form-control" })
                    </div>
                </div>
            </div>
            <div class="span6">
            </div>
        </div>
        <div class="row-fluid BorderBottom">
            <div class="span6">
                <div class="control-group">
                    <div class="controls">
                        <input type="submit" class="btn btn-small btn-success" value="Search" name="btnSearch" style="margin-left:5px;" />
                        @Html.ActionLink("  Refresh", "Index", null, new { @class = "icon-refresh btn btn-small btn-success" })
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="DataList">
        @{Html.RenderAction("List", "MenuGroup");}
    </div>

</form>

<script language="javascript" type="text/javascript">
    jQuery(document).ready(function () {
        $("#frmSearch").submit(function (e) {
            e.preventDefault();
            var data = $(this).serialize();
            $.ajax({
                type: "POST",
                url: '@Url.Action("List", "MenuGroup")',
                data: data,
                success: (function (result) {
                    $("#DataList").html(result);
                })
            })
        });
    });
</script>
<script type="text/javascript">
    $(function () {
        var oTable1 = $('#table_report').dataTable({
            "aoColumns": [
              { "bSortable": false },
                null,null,null,
              { "bSortable": false }
            ]
        });
        $('[data-rel=tooltip]').tooltip();
    })
</script>

DAQMS/DAQMS.Web/Views/MenuGroup/_CreateOrEdit.cshtml
@model  DAQMS.DomainViewModel.MenuGroupViewModel

<div class="row-fluid form-horizontal">

    <div class="row-fluid WrapperFluid">
        <div class="span6">
            <div class="control-group">
                @Html.LabelFor(model => model.ModuleId, new { @class = "control-label" })
                <div class="controls">
                    @Html.DropDownListFor(model => model.ModuleId, Model.ModuleList, new { @class = "form-control" })
                </div>
            </div>
        </div>
        <div class="span6">
            <div class="control-group">
                @Html.LabelFor(model => model.GroupName, new { @class = "control-label" })
                <div class="controls">
                    @Html.TextBoxFor(model => model.GroupName, new { @class = "form-control required" })
                </div>
            </div>
        </div>
    </div>
    
    <div class="row-fluid WrapperFluid">
        <div class="span6">
            <div class="control-group">
                @Html.LabelFor(model => model.SerialNo, new { @class = "control-label" })
                <div class="controls">
                    @Html.TextBoxFor(model => model.SerialNo, new { @class = "form-control required" })
                </div>
            </div>
        </div>
        <div class="span6">
            <div class="control-group">
                @Html.LabelFor(model => model.IconClass, new { @class = "control-label" })
                <div class="controls">
                    @Html.TextBoxFor(model => model.IconClass, new { @class = "form-control required" })
                </div>
            </div>
        </div>
    </div>
</div>

DAQMS/DAQMS.Web/Views/MenuGroup/_PartialList.cshtml
@model IList<DAQMS.DomainViewModel.MenuGroupViewModel>

<div class="row-fluid">

    <table id="table_report" class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th class="center"> SL# </th>
                <th class="center">Menu Group</th>
                <th class="center">Module</th>
                <th class="center">Sequence #</th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="center">
                        @item.rowsl
                    </td>
                    <td>
                        <a href="#">
                            @item.GroupName
                        </a>
                    </td>
                    <td>
                        @item.ModuleName
                    </td>
                    <td>
                        @item.SerialNo
                    </td>
                    <td class="td-actions">
                        <div class="center">
                            @Html.ActionLink(" ", "Edit", new { id = item.Id }, new { @class = "btn btn-mini btn-info icon-edit bigger-120" })
                            @Html.ActionLink(" ", "Delete", new { id = item.Id }, new { @class = "gridDelete btn btn-mini btn-danger icon-trash bigger-120" })
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<script type="text/javascript">

    $(function () {

        $("a.gridDelete").on("click", function () {
            deleteLinkObj = $(this);
            var confirmMessage = 'Are you sure? Do you want to delete this record?';
            var con = confirm(confirmMessage);
            if (con == true) {
                $.post(deleteLinkObj[0].href, function (obj) {
                    if (obj.Success) {
                        alert(obj.Message);
                        window.document.location = document.location.href;
                    }
                    else {
                        alert(obj.Message);
                    }
                });
            }
            return false;
        });
    });

</script>