DAQMS/DAQMS.Web/Controllers/DeviceController.cs
using Code;
using DAQMS.DomainViewModel;
using DAQMS.Service;
using DAQMS.Web.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
namespace DAQMS.Web.Controllers
{
    public class DeviceController : Controller
    {
        private readonly DeviceService _DeviceService;
        private readonly ProjectService _ProjectService;

        public DeviceController()
        {
            this._DeviceService = new DeviceService();
            this._ProjectService = new ProjectService();
        }

        public ActionResult Index()
        {
            DeviceViewModel model = new DeviceViewModel();
            model.CompanyList = PopulateDropdown.PopulateDropdownListByTable("Company");
            model.ProjectList = PopulateDropdown.PopulateDropdownListByTable("Project");

            return View(model);
        }

        public PartialViewResult List(int? page)
        {
            IList<DeviceViewModel> model = _DeviceService.GetAll();
            return PartialView("_PartialList", model);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public PartialViewResult List(int? page, DeviceViewModel model)
        {
            IList<DeviceViewModel> data = _DeviceService.GetByItem(model);
            return PartialView("_PartialList", data);
        }

        [HttpGet]
        public ActionResult Create()
        {
            DeviceViewModel model = new DeviceViewModel();
            model.CompanyList = PopulateDropdown.PopulateDropdownListByTable("Company");
            model.ProjectList = PopulateDropdown.PopulateDropdownListByTable("Project");
            model.DeviceStatusList = PopulateDropdown.PopulateDropdownListByTable("DeviceStatus");
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(DeviceViewModel model)
        {
            int returnId = -1;
            model.LoginUserID = HttpContext.User.Identity.Name;
            var strMessage = string.Empty;
            try
            {
                if (ModelState.IsValid)
                {
                    if (string.IsNullOrEmpty(strMessage))
                    {
                        returnId = _DeviceService.InsertData(model);

                        if (returnId <= 0)
                        {
                            strMessage = "Error: There was a problem while processing your request.";
                            return Content(strMessage);
                        }
                        else
                        {
                            return Content(Boolean.TrueString);
                        }
                    }
                    else
                    {
                        return Content(strMessage);
                    }
                }
                else
                {
                    strMessage = Common.GetModelStateErrorMessage(ModelState);
                    return Content(strMessage);
                }
            }
            catch (Exception ex)
            {
                strMessage = "Error: There was a problem while processing your request: " + ex.Message;
                return Content(strMessage);
            }
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            DeviceViewModel model = _DeviceService.GetIById(id);
            model.CompanyList = PopulateDropdown.PopulateDropdownListByTable("Company");
            model.ProjectList = PopulateDropdown.PopulateDropdownListByTable("Project", model.CompanyId);
            model.DeviceStatusList = PopulateDropdown.PopulateDropdownListByTable("DeviceStatus");
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(DeviceViewModel model)
        {
            int returnId = -1;
            model.LoginUserID = HttpContext.User.Identity.Name;
            var strMessage = string.Empty;
            try
            {
                if (ModelState.IsValid)
                {
                    if (string.IsNullOrEmpty(strMessage))
                    {
                        returnId = _DeviceService.UpdateData(model);

                        if (returnId <= 0)
                        {
                            strMessage = "Error: There was a problem while processing your request.";
                            return Content(strMessage);
                        }
                        else
                        {
                            return Content(Boolean.TrueString);
                        }
                    }
                    else
                    {
                        return Content(strMessage);
                    }
                }
                else
                {
                    strMessage = Common.GetModelStateErrorMessage(ModelState);
                    return Content(strMessage);
                }
            }
            catch (Exception ex)
            {
                strMessage = "Error: There was a problem while processing your request: " + ex.Message;
                return Content(strMessage);
            }
        }

        [HttpPost, ActionName("Delete")]
        public JsonResult DeleteConfirmed(int id)
        {
            int userId = -1;
            bool result = true;
            string errMsg = string.Empty;
            try
            {

                userId = _DeviceService.DeleteData(id);

                if (userId <= 0)
                {
                    result = false;
                    errMsg = "This information is already used in another scope.";
                }
                else
                {
                    result = true;
                    errMsg = "Information has been deleted successfully.";
                }
            }
            catch (Exception ex)
            {
                result = false;
                errMsg = ex.Message;
            }
            return Json(new
            {
                Success = result,
                Message = errMsg
            }, JsonRequestBehavior.AllowGet);
        }



        public JsonResult GettingCompanyWiseProject(int companyId)
        {
            IList<SelectListItem> list = new List<SelectListItem>();

            ProjectViewModel projectModel = new ProjectViewModel();
            projectModel.CompanyId = companyId;

            List<ProjectViewModel> projectList = _ProjectService.GetByItem(projectModel);

            if (projectList.Count > 0)
            {
                foreach (var item in projectList)
                {
                    list.Add(new SelectListItem { Text = item.ProjectName, Value = item.Id.ToString() });
                }
            }
            return Json(list, JsonRequestBehavior.AllowGet);
        }
    }
}

DAQMS/DAQMS.Web/Controllers/RelayController.cs
using Code;
using DAQMS.DomainViewModel;
using DAQMS.Service;
using DAQMS.Web.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
namespace DAQMS.Web.Controllers
{
    public class RelayController : Controller
    {
        private readonly RelayService _relayService;

        public RelayController()
        {
            this._relayService = new RelayService();
        }

        public ActionResult Index()
        {
            RelayViewModel model = new RelayViewModel();
            model.CompanyList = PopulateDropdown.PopulateDropdownListByTable("company");
            model.ProjectList = PopulateDropdown.PopulateDropdownListByTable("project");
            model.RelayStateList = PopulateDropdown.PopulateDropdownListByTable("relay_state");
            model.DeviceIDList = PopulateDropdown.PopulateDropdownListByTable("devices");
            model.DeviceStateList = PopulateDropdown.PopulateDropdownListByTable("device_status");


            return View(model);
        }

        public PartialViewResult List(int? page)
        {
            IList<RelayViewModel> model = _relayService.GetAll();
            return PartialView("_PartialList", model);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public PartialViewResult List(int? page, RelayViewModel model)
        {
            IList<RelayViewModel> data = _relayService.GetByItem(model);
            return PartialView("_PartialList", data);
        }

        [HttpGet]
        public ActionResult Create()
        {
            RelayViewModel model = new RelayViewModel();
            model.CompanyList = PopulateDropdown.PopulateDropdownListByTable("company");
            model.ProjectList = PopulateDropdown.PopulateDropdownListByTable("project");
            model.RelayStateList = PopulateDropdown.PopulateDropdownListByTable("relay_state");
            model.DeviceIDList = PopulateDropdown.PopulateDropdownListByTable("devices");
            model.DeviceStateList = PopulateDropdown.PopulateDropdownListByTable("device_status");
            model.RelayStatusList = PopulateDropdown.PopulateDropdownListByTable("relay_status");

            return View(model);
        }

        [HttpPost]
        public ActionResult Create(RelayViewModel model)
        {
            int returnId = -1;
            model.LoginUserID = HttpContext.User.Identity.Name;
            var strMessage = string.Empty;
            try
            {
                if (ModelState.IsValid)
                {
                    if (string.IsNullOrEmpty(strMessage))
                    {
                        returnId = _relayService.InsertData(model);

                        if (returnId <= 0)
                        {
                            strMessage = "Error: There was a problem while processing your request.";
                            return Content(strMessage);
                        }
                        else
                        {
                            return Content(Boolean.TrueString);
                        }
                    }
                    else
                    {
                        return Content(strMessage);
                    }
                }
                else
                {
                    strMessage = Common.GetModelStateErrorMessage(ModelState);
                    return Content(strMessage);
                }
            }
            catch (Exception ex)
            {
                strMessage = "Error: There was a problem while processing your request: " + ex.Message;
                return Content(strMessage);
            }
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            RelayViewModel model = _relayService.GetIById(id);
            model.CompanyList = PopulateDropdown.PopulateDropdownListByTable("company");
            model.ProjectList = PopulateDropdown.PopulateDropdownListByTable("project", model.CompanyId);
            model.RelayStateList = PopulateDropdown.PopulateDropdownListByTable("relay_state");
            model.DeviceIDList = PopulateDropdown.PopulateDropdownListByTable("devices", model.ProjectId);
            model.DeviceStateList = PopulateDropdown.PopulateDropdownListByTable("device_status");
            model.RelayStatusList = PopulateDropdown.PopulateDropdownListByTable("relay_status");
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(RelayViewModel model)
        {
            int returnId = -1;
            model.LoginUserID = HttpContext.User.Identity.Name;
            var strMessage = string.Empty;
            try
            {
                if (ModelState.IsValid)
                {
                    if (string.IsNullOrEmpty(strMessage))
                    {
                        returnId = _relayService.UpdateData(model);

                        if (returnId <= 0)
                        {
                            strMessage = "Error: There was a problem while processing your request.";
                            return Content(strMessage);
                        }
                        else
                        {
                            return Content(Boolean.TrueString);
                        }
                    }
                    else
                    {
                        return Content(strMessage);
                    }
                }
                else
                {
                    strMessage = Common.GetModelStateErrorMessage(ModelState);
                    return Content(strMessage);
                }
            }
            catch (Exception ex)
            {
                strMessage = "Error: There was a problem while processing your request: " + ex.Message;
                return Content(strMessage);
            }
        }

        [HttpPost, ActionName("Delete")]
        public JsonResult DeleteConfirmed(int id)
        {
            int userId = -1;
            bool result = true;
            string errMsg = string.Empty;
            try
            {

                userId = _relayService.DeleteData(id);

                if (userId <= 0)
                {
                    result = false;
                    errMsg = "This information is already used in another scope.";
                }
                else
                {
                    result = true;
                    errMsg = "Information has been deleted successfully.";
                }
            }
            catch (Exception ex)
            {
                result = false;
                errMsg = ex.Message;
            }
            return Json(new
            {
                Success = result,
                Message = errMsg
            }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCompanyWiseProject(int companyId)
        {
            ProjectService _ProjectService = new ProjectService();
            IList<SelectListItem> list = new List<SelectListItem>();

            ProjectViewModel projectModel = new ProjectViewModel();
            projectModel.CompanyId = companyId;

            List<ProjectViewModel> projectList = _ProjectService.GetByItem(projectModel);

            if (projectList.Count > 0)
            {
                foreach (var item in projectList)
                {
                    list.Add(new SelectListItem { Text = item.ProjectName, Value = item.Id.ToString() });
                }
            }
            return Json(list, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetProjectWiseDevice(int projectId)
        {
            DeviceService _deviceService = new DeviceService();

            IList<SelectListItem> list = new List<SelectListItem>();

            DeviceViewModel model = new DeviceViewModel();
            model.ProjectId = projectId;

            List<DeviceViewModel> itemList = _deviceService.GetByItem(model);

            if (itemList.Count > 0)
            {
                foreach (var item in itemList)
                {
                    list.Add(new SelectListItem { Text = item.DeviceID, Value = item.Id.ToString() });
                }
            }
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCompanyWiseContact(int companyId)
        {
            ContactService _contactService = new ContactService();

            IList<SelectListItem> list = new List<SelectListItem>();

            ContactViewModel model = new ContactViewModel();
            model.CompanyId = companyId;

            List<ContactViewModel> itemList = _contactService.GetByItem(model);

            if (itemList.Count > 0)
            {
                foreach (var item in itemList)
                {
                    list.Add(new SelectListItem { Text = item.ContactName, Value = item.Id.ToString() });
                }
            }
            return Json(list, JsonRequestBehavior.AllowGet);
        }
    }
}

DAQMS/DAQMS.Web/Views/Device/Create.cshtml
@model  DAQMS.DomainViewModel.DeviceViewModel
@{
    ViewBag.Title = "DAQ - Add Device";
}
@using (Html.BeginForm("Create", "Device", FormMethod.Post, new { @id = "frmSave" }))
{
    <div class="table-header">
        Create Device
    </div>
    <div class="dataTables_wrapper">
        @Html.ValidationSummary(true)
        @Html.Partial("_CreateOrEdit", Model)

        <div class="row-fluid form-horizontal">
            <div class="control-group">
                <div class="controls">
                    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-small btn-success" })
                    <button id="btnSave" name="btnSave" type="submit" class="btn btn-small btn-success" onclick="return fnValidate()">
                        Save
                    </button>
                </div>
            </div>
            <div class="control-group">
                <div class="controls">
                    <div id="ErrorMessage">
                    </div>
                    <div id="lblMsg">
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<script language="javascript" type="text/javascript">
    $(document).ready(function () {
        //required for Unit Info
        $("#frmSave").on('submit', function (e) {
            e.preventDefault();

            $("#lblMsg").html(''); $("#ErrorMessage").html('');
            var data = $(this).serialize();
            $.ajax({
                type: "POST",
                url: '@Url.Action("Create", "Device")',
                data: data,
                success: (function (result) {
                    if (result == "True") {

                        $("#lblMsg").html('Information has been saved successfully').css("color", "green");
                        $("#lblMsg").show();
                        $("#MyDialog").dialog('close');
                    }
                    else {
                        $("#ErrorMessage").html(result).css("color", "red");
                    }
                })
            })
        });
    });
</script>

DAQMS/DAQMS.Web/Views/Device/Edit.cshtml
@model DAQMS.DomainViewModel.DeviceViewModel
@{
    ViewBag.Title = "DAQ - Edit Device";
}
@using (Html.BeginForm("Edit", "Device", FormMethod.Post, new { @id = "frmEdit" }))
{
    <div class="table-header">
        Edit Device
    </div>
    <div class="dataTables_wrapper">
        @Html.ValidationSummary(true)

        @Html.HiddenFor(model => model.Id)
        @Html.Partial("_CreateOrEdit", Model)

        <div class="row-fluid form-horizontal">
            <div class="control-group">
                <div class="controls">
                    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-small btn-success" })
                    <button id="btnSave" name="btnSave" type="submit" class="btn btn-small btn-success"
                            onclick="return fnValidate()">
                        Update
                    </button>
                </div>
            </div>
            <div class="control-group">
                <div class="controls">
                    <div id="ErrorMessage">
                    </div>
                    <div id="lblMsg">
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<script language="javascript" type="text/javascript">
    $(document).ready(function () {
        //required for Unit Info
        $("#frmEdit").on('submit', function (e) {
            //Clear message
            $("#lblMsg").html(''); $("#ErrorMessage").html('');
            e.preventDefault();
            var data = $(this).serialize();
            $.ajax({
                type: "POST",
                url: '@Url.Action("Edit", "Device")',
                data: data,
                success: (function (result) {
                    if (result == "True") {
                        //show message in popup
                        $("#lblMsg").html('');
                        $("#lblMsg").html('Information has been updated successfully').css("color", "green");
                        $("#lblMsg").show();
                        $("#MyDialog").dialog('close');
                    }
                    else {
                        $("#ErrorMessage").html(result).css("color", "red");;
                    }

                    var msg = $("#lblMsg").text();
                    $("#MyDialog").dialog('close');
                })
            })
        });
    });
</script>

DAQMS/DAQMS.Web/Views/Device/Index.cshtml
@model  DAQMS.DomainViewModel.DeviceViewModel

@{
    ViewBag.Title = "List of Device";

}

<form id="frmSearch" method="post" action="">
    <div class="table-header">
        List of Device
        @Html.ActionLink("  Add New", "Create", null, new { @class = " icon-plus btn btn-small btn-success pull-right" })
    </div>

    <div class="dataTables_wrapper form-horizontal">
        <div class="row-fluid">
            <div class="span6">
                <div class="control-group">
                    @Html.LabelFor(model => model.CompanyId, new { @class = "control-label" })
                    <div class="controls">
                        @Html.DropDownListFor(model => model.CompanyId, Model.CompanyList, new { @class = "form-control", onchange = "GettingCompanyWiseProject(this)" })
                    </div>
                </div>
            </div>
            <div class="span6">
                <div class="control-group">
                    @Html.LabelFor(model => model.ProjectId, new { @class = "control-label" })
                    <div class="controls">
                        @Html.DropDownListFor(model => model.ProjectId, Model.ProjectList, new { @class = "form-control" })
                    </div>
                </div>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span6">
                <div class="control-group">
                    @Html.LabelFor(model => model.DeviceID, new { @class = "control-label" })
                    <div class="controls">
                        @Html.TextBoxFor(model => model.DeviceID, new { @class = "form-control" })
                    </div>
                </div>
            </div>
            <div class="span6">

            </div>
        </div>
        <div class="row-fluid BorderBottom">
            <div class="span6">
                <div class="control-group">
                    <div class="controls">
                        <input type="submit" class="btn btn-small btn-success" value="Search" name="btnSearch" style="margin-left:5px;" />
                        @Html.ActionLink("  Refresh", "Index", null, new { @class = "icon-refresh btn btn-small btn-success" })
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="DataList">
        @{Html.RenderAction("List", "Device");}
    </div>

</form>

<script language="javascript" type="text/javascript">
    jQuery(document).ready(function () {
        $("#frmSearch").submit(function (e) {
            e.preventDefault();
            var data = $(this).serialize();
            $.ajax({
                type: "POST",
                url: '@Url.Action("List", "Device")',
                data: data,
                success: (function (result) {
                    $("#DataList").html(result);
                    LoadGrid();
                })
            })
        });
    });
</script>

<script type="text/javascript">
    $(function () {
        var oTable1 = $('#table_report').dataTable({
            "aoColumns": [
              { "bSortable": false },
                null, null, null, null, null,
              { "bSortable": false }
            ]
        });
        $('[data-rel=tooltip]').tooltip();
    });

    function LoadGrid() {
        var oTable1 = $('#table_report').dataTable({
            "aoColumns": [
              { "bSortable": false },
                null, null, null, null, null,
              { "bSortable": false }
            ]
        });
        $('[data-rel=tooltip]').tooltip();
    }

</script>

<script type="text/javascript">

    function GettingCompanyWiseProject(selectedElement) {

        var selectedBrandId = $(selectedElement).attr('id');
        var selectedTenderValue = $(selectedElement).val();

        if (selectedTenderValue > 0) {
            url = '@Url.Action("GettingCompanyWiseProject", "Device")',

            $.post(url, { companyId: selectedTenderValue }, function (response) {

                if (response.length > 0) {

                    $("#ProjectId").empty();

                    $("#ProjectId").append($('<option>', {
                        value: '0',
                        text: 'Select'
                    }));

                    $.each(response, function (key, value) {
                        $("#ProjectId").append('<option value="' + value.Value + '">' + value.Text + '</option>');
                    });
                }
                else {
                    $("#ProjectId").empty();
                    $("#ProjectId").append($('<option>', {
                        value: '0',
                        text: 'Select'
                    }));

                    $("#ErrorMessage").show().html("" + 'No data found. Please contact with admin.' + "").css("color", "red");
                }
            });
        }
        else {
            $("#ProjectId").empty();
            $("#ProjectId").append($('<option>', {
                value: '0',
                text: 'Select'
            }));

        }
    }


</script>

DAQMS/DAQMS.Web/Views/Device/_CreateOrEdit.cshtml
@model  DAQMS.DomainViewModel.DeviceViewModel

<div class="row-fluid form-horizontal">

    <div class="row-fluid WrapperFluid">
        <div class="span6">
            <div class="control-group">
                @Html.LabelFor(model => model.CompanyId, new { @class = "control-label" })
                <div class="controls">
                    @Html.DropDownListFor(model => model.CompanyId, Model.CompanyList, new { @class = "form-control required", onchange = "GetCompanyWiseProject(this)" })
                </div>
            </div>
        </div>
        <div class="span6">
            <div class="control-group">
                @Html.LabelFor(model => model.ProjectId, new { @class = "control-label" })
                <div class="controls">
                    @Html.DropDownListFor(model => model.ProjectId, Model.ProjectList, new { @class = "form-control required" })
                </div>
            </div>
        </div>
    </div>

    <div class="row-fluid WrapperFluid">
        <div class="span6">
            <div class="control-group">
                @Html.LabelFor(model => model.DeviceID, new { @class = "control-label" })
                <div class="controls">
                    @Html.TextBoxFor(model => model.DeviceID, new { @class = "form-control required" })
                </div>
            </div>
        </div>
        <div class="span6">
            <div class="control-group">
                @Html.LabelFor(model => model.DeviceStatusId, new { @class = "control-label" })
                <div class="controls">
                    @Html.DropDownListFor(model => model.DeviceStatusId, Model.DeviceStatusList, new { @class = "form-control" })
                </div>
            </div>
        </div>
    </div>

    <div class="row-fluid WrapperFluid">
        <div class="span6">
            <div class="control-group">
                @Html.LabelFor(model => model.SiteName, new { @class = "control-label" })
                <div class="controls">
                    @Html.TextBoxFor(model => model.SiteName, new { @class = "form-control required" })
                </div>
            </div>
        </div>
        <div class="span6">
            <div class="control-group">
                @Html.LabelFor(model => model.DaqLocation, new { @class = "control-label" })
                <div class="controls">
                    @Html.TextBoxFor(model => model.DaqLocation, new { @class = "form-control required" })
                </div>
            </div>
        </div>
    </div>

    <div class="row-fluid WrapperFluid">
        <div class="span6">
            <div class="control-group">
                @Html.LabelFor(model => model.FarmwareVersion, new { @class = "control-label" })
                <div class="controls">
                    @Html.TextBoxFor(model => model.FarmwareVersion, new { @class = "form-control required" })
                </div>
            </div>
        </div>
        <div class="span6">
            <div class="control-group">
                @Html.LabelFor(model => model.Notes, new { @class = "control-label" })
                <div class="controls">
                    @Html.TextAreaFor(model => model.Notes, new { @class = "form-control" })
                </div>
            </div>
        </div>
    </div>

</div>

<script type="text/javascript">

        function GetCompanyWiseProject(selectedElement) {
            var selectedBrandId = $(selectedElement).attr('id');
            var selectedTenderValue = $(selectedElement).val();

            if (selectedTenderValue > 0) {

                $("#ErrorMessage").show().html("");
                $("#ProjectId").empty();

                $("#ProjectId").append($('<option>', {
                    value: '0',
                    text: '< Select >'
                }));

                url = '@Url.Action("GetCompanyWiseProject", "Relay")';

                $.post(url, { companyId: selectedTenderValue }, function (response) {
                    if (response.length > 0) {
                        $.each(response, function (key, value) {
                            $("#ProjectId").append('<option value="' + value.Value + '">' + value.Text + '</option>');
                        });
                    }
                    else {
                        $("#ErrorMessage").show().html("" + 'No data found. Please contact with admin.' + "").css("color", "red");
                    }
                });
            }
            else {
                $("#ProjectId").empty();
                $("#ProjectId").append($('<option>', {
                    value: '0',
                    text: '< Select >'
                }));
            }
        }

</script>