DAQMS/DAQMS.Web/Controllers/AlertSetupController.cs
using Code;
using DAQMS.Core;
using DAQMS.DomainViewModel;
using DAQMS.Service;
using DAQMS.Web.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DAQMS.Web.Controllers
{
    public class AlertSetupController : Controller
    {
        private readonly ContactService _ContactService;
        private readonly ProjectService _ProjectService;
        private readonly ProjectContactService _ProjectContactService;
        private readonly AlertSetupMasterService _AlertSetupMasterService;
        private readonly AlertSetupTempService _AlertSetupTempService;
        private readonly AlertSetupCTRService _AlertSetupCTRService;

        public AlertSetupController()
        {
            this._ContactService = new ContactService();
            this._ProjectService = new ProjectService();
            this._ProjectContactService = new ProjectContactService();
            this._AlertSetupMasterService = new AlertSetupMasterService();
            this._AlertSetupTempService = new AlertSetupTempService();
            this._AlertSetupCTRService = new AlertSetupCTRService();
        }

        public ActionResult Index()
        {
            AlertSetupMasterViewModel model = new AlertSetupMasterViewModel();
            model.CompanyList = PopulateDropdown.PopulateDropdownListByTable("company");
            model.ProjectList = PopulateDropdown.PopulateDropdownListByTable("Project");
            model.ContactNameList = PopulateDropdown.PopulateDropdownListByTable("contact");
            return View(model);
        }

        public PartialViewResult List(int? page)
        {
            IList<AlertSetupMasterViewModel> model = _AlertSetupMasterService.GetAll();
            return PartialView("_PartialList", model);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public PartialViewResult List(int? page, AlertSetupMasterViewModel model)
        {
            IList<AlertSetupMasterViewModel> data = _AlertSetupMasterService.GetByItem(model);
            return PartialView("_PartialList", data);
        }

        [HttpGet]
        public ActionResult Create()
        {
            AlertSetupMasterViewModel model = new AlertSetupMasterViewModel();
            model.CompanyList = PopulateDropdown.PopulateDropdownListByTable("company");
            model.ProjectList = PopulateDropdown.PopulateDropdownListByTable("Project");
            model.ContactNameList = PopulateDropdown.PopulateDropdownListByTable("contact");

            SensorViewModel sensorModel = new SensorViewModel();
            SensorService sensorService = new SensorService();
            sensorModel.TableName = "sensor_temp";
            List<SensorViewModel> lst = sensorService.GetByItem(sensorModel);

            model.AlertSetupTempList = new List<AlertSetupTempViewModel>();

            if (lst.Count() > 0)
            {
                foreach (var item in lst)
                {
                    AlertSetupTempViewModel obj = new AlertSetupTempViewModel();
                    obj.SensorId = item.Id;
                    obj.SensorName = item.SensorName;
                    obj.AlertSetupId = model.Id;
                    obj.LoginUserID = model.LoginUserID;
                    obj.LowTemp = 0;
                    obj.HighTemp = 0;
                    model.AlertSetupTempList.Add(obj);
                }
            }

            sensorModel.TableName = "sensor_ct";
            lst = sensorService.GetByItem(sensorModel);

            model.AlertSetupCTRList = new List<AlertSetupCTRViewModel>();

            if (lst.Count() > 0)
            {
                foreach (var item in lst)
                {
                    AlertSetupCTRViewModel obj = new AlertSetupCTRViewModel();
                    obj.SensorId = item.Id;
                    obj.SensorName = item.SensorName;
                    obj.AlertSetupId = model.Id;
                    obj.LoginUserID = model.LoginUserID;
                    obj.MaxVal = 0;
                    obj.LengthOfTime = 0;
                    model.AlertSetupCTRList.Add(obj);
                }
            }

            return View(model);
        }


        [HttpPost]
        public ActionResult Create(AlertSetupMasterViewModel model)
        {
            int returnId = -1;
            string strMessage = string.Empty;
            model.LoginUserID = HttpContext.User.Identity.Name;
            strMessage = ValidateBusinessLogic(model);

            try
            {
                if (ModelState.IsValid)
                {
                    if (string.IsNullOrEmpty(strMessage))
                    {
                        returnId = _AlertSetupMasterService.InsertData(model);

                        if (returnId <= 0)
                        {
                            strMessage = "Error: There was a problem while processing your request.";
                            return Content(strMessage);
                        }
                        else
                        {

                            #region Alert Setup Tempperature

                            List<AlertSetupTempViewModel> alertSetupTempList = model.AlertSetupTempList.Where(x => x.IsActive == true).ToList();

                            if (alertSetupTempList.Count() > 0)
                            {
                                foreach (var item in alertSetupTempList)
                                {
                                    item.AlertSetupId = returnId;
                                    item.LoginUserID = HttpContext.User.Identity.Name;
                                    _AlertSetupTempService.InsertData(item);
                                }
                            }

                            #endregion

                            #region Alert Setup CTR

                            List<AlertSetupCTRViewModel> alertSetupCTRList = model.AlertSetupCTRList.Where(x => x.IsActive == true).ToList();

                            if (alertSetupCTRList.Count() > 0)
                            {
                                foreach (var item in alertSetupCTRList)
                                {
                                    item.AlertSetupId = returnId;
                                    item.LoginUserID = HttpContext.User.Identity.Name;
                                    _AlertSetupCTRService.InsertData(item);
                                }
                            }

                            #endregion

                            return Content(Boolean.TrueString);
                        }
                    }
                    else
                    {
                        return Content(strMessage);
                    }
                }
                else
                {
                    strMessage = Common.GetModelStateErrorMessage(ModelState);
                    return Content(strMessage);
                }
            }
            catch (Exception ex)
            {
                strMessage = "Error: There was a problem while processing your request: " + ex.Message;
                return Content(strMessage);
            }
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            AlertSetupMasterViewModel model = _AlertSetupMasterService.GetIById(id);
            model.CompanyList = PopulateDropdown.PopulateDropdownListByTable("company");
            model.ProjectList = PopulateDropdown.PopulateDropdownListByTable("project", model.CompanyId);
            model.ContactNameList = PopulateDropdown.PopulateDropdownListByTable("contact", model.CompanyId);

            SensorViewModel sensorModel = new SensorViewModel();
            SensorService sensorService = new SensorService();
            sensorModel.TableName = "sensor_temp";
            List<SensorViewModel> lst = sensorService.GetByItem(sensorModel);

            model.AlertSetupTempList = new List<AlertSetupTempViewModel>();

            if (lst.Count() > 0)
            {
                AlertSetupTempViewModel Tempobj = new AlertSetupTempViewModel();
                Tempobj.AlertSetupId = model.Id;

                List<AlertSetupTempViewModel> lstTempDB = new List<AlertSetupTempViewModel>();
                lstTempDB = _AlertSetupTempService.GetByItem(Tempobj);

                foreach (var item in lst)
                {
                    AlertSetupTempViewModel obj = new AlertSetupTempViewModel();
                    obj.SensorId = item.Id;
                    obj.SensorName = item.SensorName;
                    obj.AlertSetupId = model.Id;
                    obj.LoginUserID = model.LoginUserID;
                    var assignedLst = (from tr in lstTempDB where tr.SensorId == item.Id select tr).FirstOrDefault();
                    obj.LowTemp = assignedLst != null ? assignedLst.LowTemp : 0;
                    obj.HighTemp = assignedLst != null ? assignedLst.HighTemp : 0;
                    obj.IsActive = assignedLst != null ? assignedLst.IsActive : false;

                    model.AlertSetupTempList.Add(obj);
                }
            }

            sensorModel.TableName = "sensor_ct";
            lst = sensorService.GetByItem(sensorModel);
            model.AlertSetupCTRList = new List<AlertSetupCTRViewModel>();

            if (lst.Count() > 0)
            {
                AlertSetupCTRViewModel objCTR = new AlertSetupCTRViewModel();
                objCTR.AlertSetupId = model.Id;
                List<AlertSetupCTRViewModel> objAltCTRList = new List<AlertSetupCTRViewModel>();
                objAltCTRList = _AlertSetupCTRService.GetByItem(objCTR);

                foreach (var item in lst)
                {
                    var assignCTR = (from tr in objAltCTRList where tr.SensorId == item.Id select tr).LastOrDefault();
                    AlertSetupCTRViewModel obj = new AlertSetupCTRViewModel();
                    obj.SensorId = item.Id;

DAQMS/DAQMS.Web/Views/AlertSetup/Create.cshtml
@model  DAQMS.DomainViewModel.AlertSetupMasterViewModel
@{
    ViewBag.Title = "DAQ - Add Alert Setup";
}
@using (Html.BeginForm("Create", "AlertSetup", FormMethod.Post, new { @id = "frmSave" }))
{
    <div class="table-header">
        Create Alert Setup
    </div>
    <div class="dataTables_wrapper">
        @Html.ValidationSummary(true)
        @Html.Partial("_CreateOrEdit", Model)

        <div class="row-fluid form-horizontal">
            <div class="control-group">
                <div class="controls">
                    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-small btn-success" })
                    <button id="btnSave" name="btnSave" type="submit" class="btn btn-small btn-success" onclick="return fnValidate()">
                        Save
                    </button>
                </div>
            </div>
            <div class="control-group">
                <div class="controls">
                    <div id="ErrorMessage">
                    </div>
                    <div id="lblMsg">
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<script language="javascript" type="text/javascript">
    $(document).ready(function () {

        $("#frmSave").on('submit', function (e) {
            e.preventDefault();

            $("#lblMsg").html(''); $("#ErrorMessage").html('');
            var data = $(this).serialize();
            $.ajax({
                type: "POST",
                url: '@Url.Action("Create", "AlertSetup")',
                data: data,
                success: (function (result) {
                    if (result == "True") {

                        $("#lblMsg").html('Information has been saved successfully').css("color", "green");
                        $("#lblMsg").show();
                        $("#MyDialog").dialog('close');
                    }
                    else {
                        $("#ErrorMessage").html(result).css("color", "red");
                    }
                })
            });
        });
    });
</script>

DAQMS/DAQMS.Web/Views/AlertSetup/Edit.cshtml
@model DAQMS.DomainViewModel.AlertSetupMasterViewModel
@{
    ViewBag.Title = "DAQ - Edit Alert Setup";
}
@using (Html.BeginForm("Edit", "AlertSetup", FormMethod.Post, new { @id = "frmEdit" }))
{
    <div class="table-header">
        Edit Alert Setup
    </div>
    <div class="dataTables_wrapper">
        @Html.ValidationSummary(true)

        @Html.HiddenFor(model => model.Id)
        @Html.Partial("_CreateOrEdit", Model)

        <div class="row-fluid form-horizontal">
            <div class="control-group">
                <div class="controls">
                    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-small btn-success" })
                    <button id="btnSave" name="btnSave" type="submit" class="btn btn-small btn-success"
                            onclick="return fnValidate()">
                        Update
                    </button>
                </div>
            </div>
            <div class="control-group">
                <div class="controls">
                    <div id="ErrorMessage">
                    </div>
                    <div id="lblMsg">
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<script language="javascript" type="text/javascript">
    $(document).ready(function () {
        //required for Unit Info
        $("#frmEdit").on('submit', function (e) {
            //Clear message
            $("#lblMsg").html(''); $("#ErrorMessage").html('');
            e.preventDefault();
            var data = $(this).serialize();
            $.ajax({
                type: "POST",
                url: '@Url.Action("Edit", "AlertSetup")',
                data: data,
                success: (function (result) {
                    if (result == "True") {
                        //show message in popup
                        $("#lblMsg").html('');
                        $("#lblMsg").html('Information has been updated successfully').css("color", "green");
                        $("#lblMsg").show();
                        $("#MyDialog").dialog('close');
                    }
                    else {
                        $("#ErrorMessage").html(result).css("color", "red");;
                    }

                    var msg = $("#lblMsg").text();
                    $("#MyDialog").dialog('close');
                })
            })
        });
    });
</script>

DAQMS/DAQMS.Web/Views/AlertSetup/Index.cshtml
@model  DAQMS.DomainViewModel.AlertSetupMasterViewModel

@{
    ViewBag.Title = "List of Alert Setup";

}

<form id="frmSearch" method="post" action="">
    <div class="table-header">
        List of Alert Setup
        @Html.ActionLink("  Add New", "Create", null, new { @class = " icon-plus btn btn-small btn-success pull-right" })
    </div>

    <div class="dataTables_wrapper form-horizontal">
        <div class="row-fluid">
            <div class="span6">
                <div class="control-group">
                    @Html.LabelFor(model => model.CompanyId, new { @class = "control-label" })
                    <div class="controls">
                        @Html.DropDownListFor(model => model.CompanyId, Model.CompanyList, new { @class = "form-control", onchange = "GetCompanyWiseProject(this)" })
                    </div>
                </div>
            </div>
            <div class="span6">
                <div class="control-group">
                    @Html.LabelFor(model => model.ProjectId, new { @class = "control-label" })
                    <div class="controls">
                        @Html.DropDownListFor(model => model.ProjectId, Model.ProjectList, new { @class = "form-control" })
                    </div>
                </div>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span6">
                <div class="control-group">
                    @Html.LabelFor(model => model.ContactId, new { @class = "control-label" })
                    <div class="controls">
                        @Html.DropDownListFor(model => model.ContactId, Model.ContactNameList, new { @class = "form-control" })
                    </div>
                </div>
            </div>
            <div class="span6">
                @*@Html.LabelFor(model => model.ContactName, new { @class = "control-label" })
                <div class="controls">
                    @Html.TextBoxFor(model => model.ContactName, new { @class = "form-control " })
                </div>*@
            </div>
        </div>
        <div class="row-fluid BorderBottom">
            <div class="span6">
                <div class="control-group">
                    <div class="controls">
                        <input type="submit" class="btn btn-small btn-success" value="Search" name="btnSearch" style="margin-left:5px;" />
                        @Html.ActionLink("  Refresh", "Index", null, new { @class = "icon-refresh btn btn-small btn-success" })
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="DataList">
        @{Html.RenderAction("List", "AlertSetup");}
    </div>

</form>

<script language="javascript" type="text/javascript">
    jQuery(document).ready(function () {
        $("#frmSearch").submit(function (e) {
            e.preventDefault();
            var data = $(this).serialize();
            $.ajax({
                type: "POST",
                url: '@Url.Action("List", "AlertSetup")',
                data: data,
                success: (function (result) {
                    $("#DataList").html(result);
                    LoadGrid();
                })
            })
        });
    });
</script>

<script type="text/javascript">
    $(function () {
        var oTable1 = $('#table_report').dataTable({
            "aoColumns": [
              { "bSortable": false },
                null, null, null, null, null,null,
              { "bSortable": false }
            ]
        });
        $('[data-rel=tooltip]').tooltip();
    });

    function LoadGrid() {
        var oTable1 = $('#table_report').dataTable({
            "aoColumns": [
              { "bSortable": false },
                null, null, null, null, null,null,
              { "bSortable": false }
            ]
        });
        $('[data-rel=tooltip]').tooltip();
    }
</script>

<script type="text/javascript">

    function GetCompanyWiseProject(selectedElement) {

        var selectedcompanyId = $(selectedElement).val();

        if (selectedcompanyId > 0) {

            $("#ErrorMessage").show().html("");
            $("#ProjectId").empty();
            $("#ContactId").empty();

            $("#ProjectId").append($('<option>', {
                value: '0',
                text: '< Select >'
            }));

            $("#ContactId").append($('<option>', {
                value: '0',
                text: '< Select >'
            }));

            url = '@Url.Action("GetCompanyWiseProject", "Relay")';

            $.post(url, { companyId: selectedcompanyId }, function (response) {
                if (response.length > 0) {
                    $.each(response, function (key, value) {
                        $("#ProjectId").append('<option value="' + value.Value + '">' + value.Text + '</option>');
                    });
                }
                else {
                    $("#ErrorMessage").show().html("" + 'No data found. Please contact with admin.' + "").css("color", "red");
                }
            });

            url = '@Url.Action("GetCompanyWiseContact", "Relay")';

            $.post(url, { companyId: selectedcompanyId }, function (response) {
                if (response.length > 0) {
                    $.each(response, function (key, value) {
                        $("#ContactId").append('<option value="' + value.Value + '">' + value.Text + '</option>');
                    });
                }
                else {
                    $("#ErrorMessage").show().html("" + 'No data found. Please contact with admin.' + "").css("color", "red");
                }
            });
        }
        else {
            $("#ProjectId").empty();
            $("#ContactId").empty();
            $("#ProjectId").append($('<option>', {
                value: '0',
                text: '< Select >'
            }));

            $("#ContactId").append($('<option>', {
                value: '0',
                text: '< Select >'
            }));
        }
    }

</script>

DAQMS/DAQMS.Web/Views/AlertSetup/_AlertSetupCTRList.cshtml
@model DAQMS.DomainViewModel.AlertSetupCTRViewModel
@using Helper
@using System.Web.Mvc

<tr class="dynamicRow">
    @using (Html.BeginCollectionItem("AlertSetupCTRList"))
    {
        if (Model != null)
        {
            @Html.HiddenFor(model => model.Id)
            @Html.HiddenFor(model => model.AlertSetupId)
            @Html.HiddenFor(model => model.SensorId)
        }
        <td>
            <label class="pos-rel">
                @Html.CheckBoxFor(m => Model.IsActive, new { @class = "checkBoxShow", id = string.Format("IsActive_{0}", Model.IsActive) })
                <span class="lbl"></span>
            </label>
        </td>
        <td>
            @Html.Encode(Model.SensorName)
        </td>
        <td>
            @Html.TextBoxFor(model => model.MaxVal, new { @class = "form-control required" })
        </td>
        <td>
            @Html.TextBoxFor(model => model.LengthOfTime, new { @class = "form-control required" })
        </td>
    }
</tr>

DAQMS/DAQMS.Web/Views/AlertSetup/_AlertSetupTempList.cshtml
@model DAQMS.DomainViewModel.AlertSetupTempViewModel
@using Helper
@using System.Web.Mvc

<tr class="dynamicRow">
    @using (Html.BeginCollectionItem("AlertSetupTempList"))
    {
        if (Model != null)
        {
            @Html.HiddenFor(model => model.Id)
            @Html.HiddenFor(model => model.AlertSetupId)
            @Html.HiddenFor(model => model.SensorId)
        }
        <td>
            <label class="pos-rel">
                @Html.CheckBoxFor(m => Model.IsActive, new { @class = "checkBoxShow", id = string.Format("IsActive_{0}", Model.IsActive) })
                <span class="lbl"></span>
            </label>
        </td>
        <td>
            @Html.Encode(Model.SensorName)
        </td>
        <td>
            @Html.TextBoxFor(model => model.LowTemp, new { @class = "form-control required" })
        </td>
        <td>
            @Html.TextBoxFor(model => model.HighTemp, new { @class = "form-control required" })
        </td>
    }
</tr>

DAQMS/DAQMS.Web/Views/AlertSetup/_PartialList.cshtml
@model IList<DAQMS.DomainViewModel.AlertSetupMasterViewModel>

<div class="row-fluid">

    <table id="table_report" class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th class="center"> SL# </th>
                <th class="center">Company</th>
                <th class="center">Project</th>
                <th class="center">Contact</th>
                <th class="center">Is Active T Alert?</th>
                <th class="center">Is Active CTR Alert?</th>
                <th class="center">Is Active Data Alert?</th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="center">
                        @item.rowsl
                    </td>
                    <td>
                        <a href="#">
                            @item.CompanyName
                        </a>
                    </td>

                    <td>
                        @item.ProjectName
                    </td>
                    <td>
                        @item.ContactName
                    </td>
                    <td>
                        @Html.Encode(item.IsActiveTemp == true ? "Yes" : "No")
                    </td>
                    <td>
                        @Html.Encode(item.IsActiveCTR == true ? "Yes" : "No")
                    </td>
                    <td>
                        @Html.Encode(item.IsActiveNoDataFound == true ? "Yes" : "No")
                    </td>
                    <td class="td-actions">
                        <div class="center">
                            @Html.ActionLink(" ", "Edit", new { id = item.Id }, new { @class = "btn btn-mini btn-info icon-edit bigger-120" })
                            @Html.ActionLink(" ", "Delete", new { id = item.Id }, new { @class = "gridDelete btn btn-mini btn-danger icon-trash bigger-120" })
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<script type="text/javascript">

    $(function () {

        $("a.gridDelete").on("click", function () {
            deleteLinkObj = $(this);
            var confirmMessage = 'Are you sure? Do you want to delete this record?';
            var con = confirm(confirmMessage);
            if (con == true) {
                $.post(deleteLinkObj[0].href, function (obj) {
                    if (obj.Success) {
                        alert(obj.Message);
                        window.document.location = document.location.href;
                    }
                    else {
                        alert(obj.Message);
                    }
                });
            }
            return false;
        });
    });

</script>